# Generated by Django 4.1.1 on 2022-09-21 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('data_de_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('documento', models.CharField(max_length=50, verbose_name='Nº documento')),
                ('tipo_documento', models.CharField(choices=[('CPF', 'CPF'), ('PASSAPORTE', 'Passaporte')], max_length=50, verbose_name='Tipo de documento')),
            ],
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apto', models.CharField(blank=True, max_length=5, null=True, verbose_name='APTO')),
                ('prestador_servico', models.BooleanField(default=False, verbose_name='Prestador de Serviço')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=12, verbose_name='placa')),
                ('modelo', models.CharField(max_length=20, verbose_name='modelo')),
                ('cor', models.CharField(max_length=30, verbose_name='cor')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apto', models.CharField(max_length=5, verbose_name='APTO')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='ControleAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada_saida', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10, verbose_name='Entrada e saída')),
                ('horario', models.DateTimeField(auto_now_add=True, verbose_name='Horário')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.pessoa')),
                ('veiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.veiculo')),
            ],
        ),
    ]
